/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AvatarGenerationRouteImport } from './routes/avatar-generation'
import { Route as IndexRouteImport } from './routes/index'

const AvatarGenerationRoute = AvatarGenerationRouteImport.update({
  id: '/avatar-generation',
  path: '/avatar-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar-generation': typeof AvatarGenerationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar-generation': typeof AvatarGenerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar-generation': typeof AvatarGenerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avatar-generation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avatar-generation'
  id: '__root__' | '/' | '/avatar-generation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarGenerationRoute: typeof AvatarGenerationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/avatar-generation': {
      id: '/avatar-generation'
      path: '/avatar-generation'
      fullPath: '/avatar-generation'
      preLoaderRoute: typeof AvatarGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarGenerationRoute: AvatarGenerationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
