/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutGenerateRouteImport } from './routes/_layout/generate'
import { Route as LayoutAvatarGenerationRouteImport } from './routes/_layout/avatar-generation'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutAlbumsIndexRouteImport } from './routes/_layout/albums/index'
import { Route as LayoutAlbumsAlbumIdRouteImport } from './routes/_layout/albums/$albumId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGenerateRoute = LayoutGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAvatarGenerationRoute = LayoutAvatarGenerationRouteImport.update({
  id: '/avatar-generation',
  path: '/avatar-generation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlbumsIndexRoute = LayoutAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAlbumsAlbumIdRoute = LayoutAlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof LayoutAboutRoute
  '/avatar-generation': typeof LayoutAvatarGenerationRoute
  '/generate': typeof LayoutGenerateRoute
  '/settings': typeof LayoutSettingsRoute
  '/albums/$albumId': typeof LayoutAlbumsAlbumIdRoute
  '/albums/': typeof LayoutAlbumsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/about': typeof LayoutAboutRoute
  '/avatar-generation': typeof LayoutAvatarGenerationRoute
  '/generate': typeof LayoutGenerateRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/albums/$albumId': typeof LayoutAlbumsAlbumIdRoute
  '/albums': typeof LayoutAlbumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/avatar-generation': typeof LayoutAvatarGenerationRoute
  '/_layout/generate': typeof LayoutGenerateRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/albums/$albumId': typeof LayoutAlbumsAlbumIdRoute
  '/_layout/albums/': typeof LayoutAlbumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/avatar-generation'
    | '/generate'
    | '/settings'
    | '/albums/$albumId'
    | '/albums/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/avatar-generation'
    | '/generate'
    | '/settings'
    | '/'
    | '/albums/$albumId'
    | '/albums'
  id:
    | '__root__'
    | '/_layout'
    | '/sign-in'
    | '/sign-up'
    | '/_layout/about'
    | '/_layout/avatar-generation'
    | '/_layout/generate'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/albums/$albumId'
    | '/_layout/albums/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/generate': {
      id: '/_layout/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof LayoutGenerateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/avatar-generation': {
      id: '/_layout/avatar-generation'
      path: '/avatar-generation'
      fullPath: '/avatar-generation'
      preLoaderRoute: typeof LayoutAvatarGenerationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/albums/': {
      id: '/_layout/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof LayoutAlbumsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/albums/$albumId': {
      id: '/_layout/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof LayoutAlbumsAlbumIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutAvatarGenerationRoute: typeof LayoutAvatarGenerationRoute
  LayoutGenerateRoute: typeof LayoutGenerateRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAlbumsAlbumIdRoute: typeof LayoutAlbumsAlbumIdRoute
  LayoutAlbumsIndexRoute: typeof LayoutAlbumsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutAvatarGenerationRoute: LayoutAvatarGenerationRoute,
  LayoutGenerateRoute: LayoutGenerateRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAlbumsAlbumIdRoute: LayoutAlbumsAlbumIdRoute,
  LayoutAlbumsIndexRoute: LayoutAlbumsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
